// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/practical-coder/hdt/client/maps"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationMapsClearRuntimeMapCmd returns a cmd to handle operation clearRuntimeMap
func makeOperationMapsClearRuntimeMapCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "clearRuntimeMap",
		Short: `Remove all map entries from the map file.`,
		RunE:  runOperationMapsClearRuntimeMap,
	}

	if err := registerOperationMapsClearRuntimeMapParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationMapsClearRuntimeMap uses cmd flags to call endpoint api
func runOperationMapsClearRuntimeMap(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := maps.NewClearRuntimeMapParams()
	if err, _ := retrieveOperationMapsClearRuntimeMapForceDeleteFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationMapsClearRuntimeMapForceSyncFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationMapsClearRuntimeMapNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationMapsClearRuntimeMapResult(appCli.Maps.ClearRuntimeMap(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationMapsClearRuntimeMapParamFlags registers all flags needed to fill params
func registerOperationMapsClearRuntimeMapParamFlags(cmd *cobra.Command) error {
	if err := registerOperationMapsClearRuntimeMapForceDeleteParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationMapsClearRuntimeMapForceSyncParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationMapsClearRuntimeMapNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationMapsClearRuntimeMapForceDeleteParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	forceDeleteDescription := `If true, deletes file from disk`

	var forceDeleteFlagName string
	if cmdPrefix == "" {
		forceDeleteFlagName = "forceDelete"
	} else {
		forceDeleteFlagName = fmt.Sprintf("%v.forceDelete", cmdPrefix)
	}

	var forceDeleteFlagDefault bool

	_ = cmd.PersistentFlags().Bool(forceDeleteFlagName, forceDeleteFlagDefault, forceDeleteDescription)

	return nil
}
func registerOperationMapsClearRuntimeMapForceSyncParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	forceSyncDescription := `If true, immediately syncs changes to disk`

	var forceSyncFlagName string
	if cmdPrefix == "" {
		forceSyncFlagName = "force_sync"
	} else {
		forceSyncFlagName = fmt.Sprintf("%v.force_sync", cmdPrefix)
	}

	var forceSyncFlagDefault bool

	_ = cmd.PersistentFlags().Bool(forceSyncFlagName, forceSyncFlagDefault, forceSyncDescription)

	return nil
}
func registerOperationMapsClearRuntimeMapNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	nameDescription := `Required. Map file name`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}

func retrieveOperationMapsClearRuntimeMapForceDeleteFlag(m *maps.ClearRuntimeMapParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("forceDelete") {

		var forceDeleteFlagName string
		if cmdPrefix == "" {
			forceDeleteFlagName = "forceDelete"
		} else {
			forceDeleteFlagName = fmt.Sprintf("%v.forceDelete", cmdPrefix)
		}

		forceDeleteFlagValue, err := cmd.Flags().GetBool(forceDeleteFlagName)
		if err != nil {
			return err, false
		}
		m.ForceDelete = &forceDeleteFlagValue

	}
	return nil, retAdded
}
func retrieveOperationMapsClearRuntimeMapForceSyncFlag(m *maps.ClearRuntimeMapParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("force_sync") {

		var forceSyncFlagName string
		if cmdPrefix == "" {
			forceSyncFlagName = "force_sync"
		} else {
			forceSyncFlagName = fmt.Sprintf("%v.force_sync", cmdPrefix)
		}

		forceSyncFlagValue, err := cmd.Flags().GetBool(forceSyncFlagName)
		if err != nil {
			return err, false
		}
		m.ForceSync = &forceSyncFlagValue

	}
	return nil, retAdded
}
func retrieveOperationMapsClearRuntimeMapNameFlag(m *maps.ClearRuntimeMapParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = nameFlagValue

	}
	return nil, retAdded
}

// parseOperationMapsClearRuntimeMapResult parses request result and return the string content
func parseOperationMapsClearRuntimeMapResult(resp0 *maps.ClearRuntimeMapNoContent, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*maps.ClearRuntimeMapDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning clearRuntimeMapNoContent is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*maps.ClearRuntimeMapNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response clearRuntimeMapNoContent is not supported by go-swagger cli yet.

	return "", nil
}
