// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/haproxytech/client-native/v4/models"
	"github.com/practical-coder/hdt/client/nameserver"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationNameserverCreateNameserverCmd returns a cmd to handle operation createNameserver
func makeOperationNameserverCreateNameserverCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "createNameserver",
		Short: `Adds a new nameserver to the resolvers section.`,
		RunE:  runOperationNameserverCreateNameserver,
	}

	if err := registerOperationNameserverCreateNameserverParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationNameserverCreateNameserver uses cmd flags to call endpoint api
func runOperationNameserverCreateNameserver(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := nameserver.NewCreateNameserverParams()
	if err, _ := retrieveOperationNameserverCreateNameserverDataFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationNameserverCreateNameserverForceReloadFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationNameserverCreateNameserverResolverFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationNameserverCreateNameserverTransactionIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationNameserverCreateNameserverVersionFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationNameserverCreateNameserverResult(appCli.Nameserver.CreateNameserver(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationNameserverCreateNameserverParamFlags registers all flags needed to fill params
func registerOperationNameserverCreateNameserverParamFlags(cmd *cobra.Command) error {
	if err := registerOperationNameserverCreateNameserverDataParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationNameserverCreateNameserverForceReloadParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationNameserverCreateNameserverResolverParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationNameserverCreateNameserverTransactionIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationNameserverCreateNameserverVersionParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationNameserverCreateNameserverDataParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var dataFlagName string
	if cmdPrefix == "" {
		dataFlagName = "data"
	} else {
		dataFlagName = fmt.Sprintf("%v.data", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(dataFlagName, "", "Optional json string for [data]. ")

	// add flags for body
	if err := registerModelNameserverFlags(0, "nameserver", cmd); err != nil {
		return err
	}

	return nil
}
func registerOperationNameserverCreateNameserverForceReloadParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	forceReloadDescription := `If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.`

	var forceReloadFlagName string
	if cmdPrefix == "" {
		forceReloadFlagName = "force_reload"
	} else {
		forceReloadFlagName = fmt.Sprintf("%v.force_reload", cmdPrefix)
	}

	var forceReloadFlagDefault bool

	_ = cmd.PersistentFlags().Bool(forceReloadFlagName, forceReloadFlagDefault, forceReloadDescription)

	return nil
}
func registerOperationNameserverCreateNameserverResolverParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	resolverDescription := `Required. Parent resolver name`

	var resolverFlagName string
	if cmdPrefix == "" {
		resolverFlagName = "resolver"
	} else {
		resolverFlagName = fmt.Sprintf("%v.resolver", cmdPrefix)
	}

	var resolverFlagDefault string

	_ = cmd.PersistentFlags().String(resolverFlagName, resolverFlagDefault, resolverDescription)

	return nil
}
func registerOperationNameserverCreateNameserverTransactionIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	transactionIdDescription := `ID of the transaction where we want to add the operation. Cannot be used when version is specified.`

	var transactionIdFlagName string
	if cmdPrefix == "" {
		transactionIdFlagName = "transaction_id"
	} else {
		transactionIdFlagName = fmt.Sprintf("%v.transaction_id", cmdPrefix)
	}

	var transactionIdFlagDefault string

	_ = cmd.PersistentFlags().String(transactionIdFlagName, transactionIdFlagDefault, transactionIdDescription)

	return nil
}
func registerOperationNameserverCreateNameserverVersionParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	versionDescription := `Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.`

	var versionFlagName string
	if cmdPrefix == "" {
		versionFlagName = "version"
	} else {
		versionFlagName = fmt.Sprintf("%v.version", cmdPrefix)
	}

	var versionFlagDefault int64

	_ = cmd.PersistentFlags().Int64(versionFlagName, versionFlagDefault, versionDescription)

	return nil
}

func retrieveOperationNameserverCreateNameserverDataFlag(m *nameserver.CreateNameserverParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("data") {
		// Read data string from cmd and unmarshal
		dataValueStr, err := cmd.Flags().GetString("data")
		if err != nil {
			return err, false
		}

		dataValue := models.Nameserver{}
		if err := json.Unmarshal([]byte(dataValueStr), &dataValue); err != nil {
			return fmt.Errorf("cannot unmarshal data string in models.Nameserver: %v", err), false
		}
		m.Data = &dataValue
	}
	dataValueModel := m.Data
	if swag.IsZero(dataValueModel) {
		dataValueModel = &models.Nameserver{}
	}
	err, added := retrieveModelNameserverFlags(0, dataValueModel, "nameserver", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Data = dataValueModel
	}
	if dryRun && debug {

		dataValueDebugBytes, err := json.Marshal(m.Data)
		if err != nil {
			return err, false
		}
		logDebugf("Data dry-run payload: %v", string(dataValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}
func retrieveOperationNameserverCreateNameserverForceReloadFlag(m *nameserver.CreateNameserverParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("force_reload") {

		var forceReloadFlagName string
		if cmdPrefix == "" {
			forceReloadFlagName = "force_reload"
		} else {
			forceReloadFlagName = fmt.Sprintf("%v.force_reload", cmdPrefix)
		}

		forceReloadFlagValue, err := cmd.Flags().GetBool(forceReloadFlagName)
		if err != nil {
			return err, false
		}
		m.ForceReload = &forceReloadFlagValue

	}
	return nil, retAdded
}
func retrieveOperationNameserverCreateNameserverResolverFlag(m *nameserver.CreateNameserverParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("resolver") {

		var resolverFlagName string
		if cmdPrefix == "" {
			resolverFlagName = "resolver"
		} else {
			resolverFlagName = fmt.Sprintf("%v.resolver", cmdPrefix)
		}

		resolverFlagValue, err := cmd.Flags().GetString(resolverFlagName)
		if err != nil {
			return err, false
		}
		m.Resolver = resolverFlagValue

	}
	return nil, retAdded
}
func retrieveOperationNameserverCreateNameserverTransactionIDFlag(m *nameserver.CreateNameserverParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("transaction_id") {

		var transactionIdFlagName string
		if cmdPrefix == "" {
			transactionIdFlagName = "transaction_id"
		} else {
			transactionIdFlagName = fmt.Sprintf("%v.transaction_id", cmdPrefix)
		}

		transactionIdFlagValue, err := cmd.Flags().GetString(transactionIdFlagName)
		if err != nil {
			return err, false
		}
		m.TransactionID = &transactionIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationNameserverCreateNameserverVersionFlag(m *nameserver.CreateNameserverParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("version") {

		var versionFlagName string
		if cmdPrefix == "" {
			versionFlagName = "version"
		} else {
			versionFlagName = fmt.Sprintf("%v.version", cmdPrefix)
		}

		versionFlagValue, err := cmd.Flags().GetInt64(versionFlagName)
		if err != nil {
			return err, false
		}
		m.Version = &versionFlagValue

	}
	return nil, retAdded
}

// parseOperationNameserverCreateNameserverResult parses request result and return the string content
func parseOperationNameserverCreateNameserverResult(resp0 *nameserver.CreateNameserverCreated, resp1 *nameserver.CreateNameserverAccepted, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*nameserver.CreateNameserverDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*nameserver.CreateNameserverCreated)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*nameserver.CreateNameserverAccepted)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*nameserver.CreateNameserverBadRequest)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*nameserver.CreateNameserverConflict)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
		msgStr, err := json.Marshal(resp1.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
