// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/practical-coder/hdt/client/storage"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationStorageDeleteStorageMapCmd returns a cmd to handle operation deleteStorageMap
func makeOperationStorageDeleteStorageMapCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "deleteStorageMap",
		Short: `Deletes a managed map file from disk.`,
		RunE:  runOperationStorageDeleteStorageMap,
	}

	if err := registerOperationStorageDeleteStorageMapParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationStorageDeleteStorageMap uses cmd flags to call endpoint api
func runOperationStorageDeleteStorageMap(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := storage.NewDeleteStorageMapParams()
	if err, _ := retrieveOperationStorageDeleteStorageMapNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationStorageDeleteStorageMapResult(appCli.Storage.DeleteStorageMap(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationStorageDeleteStorageMapParamFlags registers all flags needed to fill params
func registerOperationStorageDeleteStorageMapParamFlags(cmd *cobra.Command) error {
	if err := registerOperationStorageDeleteStorageMapNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationStorageDeleteStorageMapNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	nameDescription := `Required. Map file storage_name`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}

func retrieveOperationStorageDeleteStorageMapNameFlag(m *storage.DeleteStorageMapParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = nameFlagValue

	}
	return nil, retAdded
}

// parseOperationStorageDeleteStorageMapResult parses request result and return the string content
func parseOperationStorageDeleteStorageMapResult(resp0 *storage.DeleteStorageMapNoContent, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*storage.DeleteStorageMapDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning deleteStorageMapNoContent is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*storage.DeleteStorageMapNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response deleteStorageMapNoContent is not supported by go-swagger cli yet.

	return "", nil
}
