// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/practical-coder/hdt/client/reloads"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationReloadsGetReloadCmd returns a cmd to handle operation getReload
func makeOperationReloadsGetReloadCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getReload",
		Short: `Returns one HAProxy reload status.`,
		RunE:  runOperationReloadsGetReload,
	}

	if err := registerOperationReloadsGetReloadParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationReloadsGetReload uses cmd flags to call endpoint api
func runOperationReloadsGetReload(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := reloads.NewGetReloadParams()
	if err, _ := retrieveOperationReloadsGetReloadIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationReloadsGetReloadResult(appCli.Reloads.GetReload(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationReloadsGetReloadParamFlags registers all flags needed to fill params
func registerOperationReloadsGetReloadParamFlags(cmd *cobra.Command) error {
	if err := registerOperationReloadsGetReloadIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationReloadsGetReloadIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Reload id`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationReloadsGetReloadIDFlag(m *reloads.GetReloadParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationReloadsGetReloadResult parses request result and return the string content
func parseOperationReloadsGetReloadResult(resp0 *reloads.GetReloadOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*reloads.GetReloadDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*reloads.GetReloadOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*reloads.GetReloadNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
