// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/haproxytech/client-native/v4/models"
	"github.com/practical-coder/hdt/client/nameserver"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationNameserverGetNameserverCmd returns a cmd to handle operation getNameserver
func makeOperationNameserverGetNameserverCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getNameserver",
		Short: `Returns one nameserver configuration by it's name.`,
		RunE:  runOperationNameserverGetNameserver,
	}

	if err := registerOperationNameserverGetNameserverParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationNameserverGetNameserver uses cmd flags to call endpoint api
func runOperationNameserverGetNameserver(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := nameserver.NewGetNameserverParams()
	if err, _ := retrieveOperationNameserverGetNameserverNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationNameserverGetNameserverResolverFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationNameserverGetNameserverTransactionIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationNameserverGetNameserverResult(appCli.Nameserver.GetNameserver(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationNameserverGetNameserverParamFlags registers all flags needed to fill params
func registerOperationNameserverGetNameserverParamFlags(cmd *cobra.Command) error {
	if err := registerOperationNameserverGetNameserverNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationNameserverGetNameserverResolverParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationNameserverGetNameserverTransactionIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationNameserverGetNameserverNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	nameDescription := `Required. Nameserver name`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}
func registerOperationNameserverGetNameserverResolverParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	resolverDescription := `Required. Parent resolver name`

	var resolverFlagName string
	if cmdPrefix == "" {
		resolverFlagName = "resolver"
	} else {
		resolverFlagName = fmt.Sprintf("%v.resolver", cmdPrefix)
	}

	var resolverFlagDefault string

	_ = cmd.PersistentFlags().String(resolverFlagName, resolverFlagDefault, resolverDescription)

	return nil
}
func registerOperationNameserverGetNameserverTransactionIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	transactionIdDescription := `ID of the transaction where we want to add the operation. Cannot be used when version is specified.`

	var transactionIdFlagName string
	if cmdPrefix == "" {
		transactionIdFlagName = "transaction_id"
	} else {
		transactionIdFlagName = fmt.Sprintf("%v.transaction_id", cmdPrefix)
	}

	var transactionIdFlagDefault string

	_ = cmd.PersistentFlags().String(transactionIdFlagName, transactionIdFlagDefault, transactionIdDescription)

	return nil
}

func retrieveOperationNameserverGetNameserverNameFlag(m *nameserver.GetNameserverParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = nameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationNameserverGetNameserverResolverFlag(m *nameserver.GetNameserverParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("resolver") {

		var resolverFlagName string
		if cmdPrefix == "" {
			resolverFlagName = "resolver"
		} else {
			resolverFlagName = fmt.Sprintf("%v.resolver", cmdPrefix)
		}

		resolverFlagValue, err := cmd.Flags().GetString(resolverFlagName)
		if err != nil {
			return err, false
		}
		m.Resolver = resolverFlagValue

	}
	return nil, retAdded
}
func retrieveOperationNameserverGetNameserverTransactionIDFlag(m *nameserver.GetNameserverParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("transaction_id") {

		var transactionIdFlagName string
		if cmdPrefix == "" {
			transactionIdFlagName = "transaction_id"
		} else {
			transactionIdFlagName = fmt.Sprintf("%v.transaction_id", cmdPrefix)
		}

		transactionIdFlagValue, err := cmd.Flags().GetString(transactionIdFlagName)
		if err != nil {
			return err, false
		}
		m.TransactionID = &transactionIdFlagValue

	}
	return nil, retAdded
}

// parseOperationNameserverGetNameserverResult parses request result and return the string content
func parseOperationNameserverGetNameserverResult(resp0 *nameserver.GetNameserverOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*nameserver.GetNameserverDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*nameserver.GetNameserverOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*nameserver.GetNameserverNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelGetNameserverOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerGetNameserverOKBodyVersion(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerGetNameserverOKBodyData(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerGetNameserverOKBodyVersion(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	versionDescription := ``

	var versionFlagName string
	if cmdPrefix == "" {
		versionFlagName = "_version"
	} else {
		versionFlagName = fmt.Sprintf("%v._version", cmdPrefix)
	}

	var versionFlagDefault int64

	_ = cmd.PersistentFlags().Int64(versionFlagName, versionFlagDefault, versionDescription)

	return nil
}

func registerGetNameserverOKBodyData(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var dataFlagName string
	if cmdPrefix == "" {
		dataFlagName = "data"
	} else {
		dataFlagName = fmt.Sprintf("%v.data", cmdPrefix)
	}

	if err := registerModelNameserverFlags(depth+1, dataFlagName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGetNameserverOKBodyFlags(depth int, m *nameserver.GetNameserverOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, versionAdded := retrieveGetNameserverOKBodyVersionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || versionAdded

	err, dataAdded := retrieveGetNameserverOKBodyDataFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || dataAdded

	return nil, retAdded
}

func retrieveGetNameserverOKBodyVersionFlags(depth int, m *nameserver.GetNameserverOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	versionFlagName := fmt.Sprintf("%v._version", cmdPrefix)
	if cmd.Flags().Changed(versionFlagName) {

		var versionFlagName string
		if cmdPrefix == "" {
			versionFlagName = "_version"
		} else {
			versionFlagName = fmt.Sprintf("%v._version", cmdPrefix)
		}

		versionFlagValue, err := cmd.Flags().GetInt64(versionFlagName)
		if err != nil {
			return err, false
		}
		m.Version = versionFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveGetNameserverOKBodyDataFlags(depth int, m *nameserver.GetNameserverOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	dataFlagName := fmt.Sprintf("%v.data", cmdPrefix)
	if cmd.Flags().Changed(dataFlagName) {
		// info: complex object data models.Nameserver is retrieved outside this Changed() block
	}
	dataFlagValue := m.Data
	if swag.IsZero(dataFlagValue) {
		dataFlagValue = &models.Nameserver{}
	}

	err, dataAdded := retrieveModelNameserverFlags(depth+1, dataFlagValue, dataFlagName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || dataAdded
	if dataAdded {
		m.Data = dataFlagValue
	}

	return nil, retAdded
}
