// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/haproxytech/client-native/v4/models"
	"github.com/practical-coder/hdt/client/server_template"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationServerTemplateGetServerTemplateCmd returns a cmd to handle operation getServerTemplate
func makeOperationServerTemplateGetServerTemplateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getServerTemplate",
		Short: `Returns one server template configuration by it's prefix in the specified backend.`,
		RunE:  runOperationServerTemplateGetServerTemplate,
	}

	if err := registerOperationServerTemplateGetServerTemplateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationServerTemplateGetServerTemplate uses cmd flags to call endpoint api
func runOperationServerTemplateGetServerTemplate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := server_template.NewGetServerTemplateParams()
	if err, _ := retrieveOperationServerTemplateGetServerTemplateBackendFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationServerTemplateGetServerTemplatePrefixFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationServerTemplateGetServerTemplateTransactionIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationServerTemplateGetServerTemplateResult(appCli.ServerTemplate.GetServerTemplate(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationServerTemplateGetServerTemplateParamFlags registers all flags needed to fill params
func registerOperationServerTemplateGetServerTemplateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationServerTemplateGetServerTemplateBackendParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationServerTemplateGetServerTemplatePrefixParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationServerTemplateGetServerTemplateTransactionIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationServerTemplateGetServerTemplateBackendParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	backendDescription := `Required. Parent backend name`

	var backendFlagName string
	if cmdPrefix == "" {
		backendFlagName = "backend"
	} else {
		backendFlagName = fmt.Sprintf("%v.backend", cmdPrefix)
	}

	var backendFlagDefault string

	_ = cmd.PersistentFlags().String(backendFlagName, backendFlagDefault, backendDescription)

	return nil
}
func registerOperationServerTemplateGetServerTemplatePrefixParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	prefixDescription := `Required. Server template prefix`

	var prefixFlagName string
	if cmdPrefix == "" {
		prefixFlagName = "prefix"
	} else {
		prefixFlagName = fmt.Sprintf("%v.prefix", cmdPrefix)
	}

	var prefixFlagDefault string

	_ = cmd.PersistentFlags().String(prefixFlagName, prefixFlagDefault, prefixDescription)

	return nil
}
func registerOperationServerTemplateGetServerTemplateTransactionIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	transactionIdDescription := `ID of the transaction where we want to add the operation. Cannot be used when version is specified.`

	var transactionIdFlagName string
	if cmdPrefix == "" {
		transactionIdFlagName = "transaction_id"
	} else {
		transactionIdFlagName = fmt.Sprintf("%v.transaction_id", cmdPrefix)
	}

	var transactionIdFlagDefault string

	_ = cmd.PersistentFlags().String(transactionIdFlagName, transactionIdFlagDefault, transactionIdDescription)

	return nil
}

func retrieveOperationServerTemplateGetServerTemplateBackendFlag(m *server_template.GetServerTemplateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("backend") {

		var backendFlagName string
		if cmdPrefix == "" {
			backendFlagName = "backend"
		} else {
			backendFlagName = fmt.Sprintf("%v.backend", cmdPrefix)
		}

		backendFlagValue, err := cmd.Flags().GetString(backendFlagName)
		if err != nil {
			return err, false
		}
		m.Backend = backendFlagValue

	}
	return nil, retAdded
}
func retrieveOperationServerTemplateGetServerTemplatePrefixFlag(m *server_template.GetServerTemplateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("prefix") {

		var prefixFlagName string
		if cmdPrefix == "" {
			prefixFlagName = "prefix"
		} else {
			prefixFlagName = fmt.Sprintf("%v.prefix", cmdPrefix)
		}

		prefixFlagValue, err := cmd.Flags().GetString(prefixFlagName)
		if err != nil {
			return err, false
		}
		m.Prefix = prefixFlagValue

	}
	return nil, retAdded
}
func retrieveOperationServerTemplateGetServerTemplateTransactionIDFlag(m *server_template.GetServerTemplateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("transaction_id") {

		var transactionIdFlagName string
		if cmdPrefix == "" {
			transactionIdFlagName = "transaction_id"
		} else {
			transactionIdFlagName = fmt.Sprintf("%v.transaction_id", cmdPrefix)
		}

		transactionIdFlagValue, err := cmd.Flags().GetString(transactionIdFlagName)
		if err != nil {
			return err, false
		}
		m.TransactionID = &transactionIdFlagValue

	}
	return nil, retAdded
}

// parseOperationServerTemplateGetServerTemplateResult parses request result and return the string content
func parseOperationServerTemplateGetServerTemplateResult(resp0 *server_template.GetServerTemplateOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*server_template.GetServerTemplateDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*server_template.GetServerTemplateOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*server_template.GetServerTemplateNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelGetServerTemplateOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerGetServerTemplateOKBodyVersion(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerGetServerTemplateOKBodyData(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerGetServerTemplateOKBodyVersion(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	versionDescription := ``

	var versionFlagName string
	if cmdPrefix == "" {
		versionFlagName = "_version"
	} else {
		versionFlagName = fmt.Sprintf("%v._version", cmdPrefix)
	}

	var versionFlagDefault int64

	_ = cmd.PersistentFlags().Int64(versionFlagName, versionFlagDefault, versionDescription)

	return nil
}

func registerGetServerTemplateOKBodyData(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var dataFlagName string
	if cmdPrefix == "" {
		dataFlagName = "data"
	} else {
		dataFlagName = fmt.Sprintf("%v.data", cmdPrefix)
	}

	if err := registerModelServerTemplateFlags(depth+1, dataFlagName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGetServerTemplateOKBodyFlags(depth int, m *server_template.GetServerTemplateOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, versionAdded := retrieveGetServerTemplateOKBodyVersionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || versionAdded

	err, dataAdded := retrieveGetServerTemplateOKBodyDataFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || dataAdded

	return nil, retAdded
}

func retrieveGetServerTemplateOKBodyVersionFlags(depth int, m *server_template.GetServerTemplateOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	versionFlagName := fmt.Sprintf("%v._version", cmdPrefix)
	if cmd.Flags().Changed(versionFlagName) {

		var versionFlagName string
		if cmdPrefix == "" {
			versionFlagName = "_version"
		} else {
			versionFlagName = fmt.Sprintf("%v._version", cmdPrefix)
		}

		versionFlagValue, err := cmd.Flags().GetInt64(versionFlagName)
		if err != nil {
			return err, false
		}
		m.Version = versionFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveGetServerTemplateOKBodyDataFlags(depth int, m *server_template.GetServerTemplateOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	dataFlagName := fmt.Sprintf("%v.data", cmdPrefix)
	if cmd.Flags().Changed(dataFlagName) {
		// info: complex object data models.ServerTemplate is retrieved outside this Changed() block
	}
	dataFlagValue := m.Data
	if swag.IsZero(dataFlagValue) {
		dataFlagValue = &models.ServerTemplate{}
	}

	err, dataAdded := retrieveModelServerTemplateFlags(depth+1, dataFlagValue, dataFlagName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || dataAdded
	if dataAdded {
		m.Data = dataFlagValue
	}

	return nil, retAdded
}
