// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/practical-coder/hdt/client/nameserver"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationNameserverGetNameserversCmd returns a cmd to handle operation getNameservers
func makeOperationNameserverGetNameserversCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getNameservers",
		Short: `Returns an array of all configured nameservers.`,
		RunE:  runOperationNameserverGetNameservers,
	}

	if err := registerOperationNameserverGetNameserversParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationNameserverGetNameservers uses cmd flags to call endpoint api
func runOperationNameserverGetNameservers(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := nameserver.NewGetNameserversParams()
	if err, _ := retrieveOperationNameserverGetNameserversResolverFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationNameserverGetNameserversTransactionIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationNameserverGetNameserversResult(appCli.Nameserver.GetNameservers(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationNameserverGetNameserversParamFlags registers all flags needed to fill params
func registerOperationNameserverGetNameserversParamFlags(cmd *cobra.Command) error {
	if err := registerOperationNameserverGetNameserversResolverParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationNameserverGetNameserversTransactionIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationNameserverGetNameserversResolverParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	resolverDescription := `Required. Parent resolver name`

	var resolverFlagName string
	if cmdPrefix == "" {
		resolverFlagName = "resolver"
	} else {
		resolverFlagName = fmt.Sprintf("%v.resolver", cmdPrefix)
	}

	var resolverFlagDefault string

	_ = cmd.PersistentFlags().String(resolverFlagName, resolverFlagDefault, resolverDescription)

	return nil
}
func registerOperationNameserverGetNameserversTransactionIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	transactionIdDescription := `ID of the transaction where we want to add the operation. Cannot be used when version is specified.`

	var transactionIdFlagName string
	if cmdPrefix == "" {
		transactionIdFlagName = "transaction_id"
	} else {
		transactionIdFlagName = fmt.Sprintf("%v.transaction_id", cmdPrefix)
	}

	var transactionIdFlagDefault string

	_ = cmd.PersistentFlags().String(transactionIdFlagName, transactionIdFlagDefault, transactionIdDescription)

	return nil
}

func retrieveOperationNameserverGetNameserversResolverFlag(m *nameserver.GetNameserversParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("resolver") {

		var resolverFlagName string
		if cmdPrefix == "" {
			resolverFlagName = "resolver"
		} else {
			resolverFlagName = fmt.Sprintf("%v.resolver", cmdPrefix)
		}

		resolverFlagValue, err := cmd.Flags().GetString(resolverFlagName)
		if err != nil {
			return err, false
		}
		m.Resolver = resolverFlagValue

	}
	return nil, retAdded
}
func retrieveOperationNameserverGetNameserversTransactionIDFlag(m *nameserver.GetNameserversParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("transaction_id") {

		var transactionIdFlagName string
		if cmdPrefix == "" {
			transactionIdFlagName = "transaction_id"
		} else {
			transactionIdFlagName = fmt.Sprintf("%v.transaction_id", cmdPrefix)
		}

		transactionIdFlagValue, err := cmd.Flags().GetString(transactionIdFlagName)
		if err != nil {
			return err, false
		}
		m.TransactionID = &transactionIdFlagValue

	}
	return nil, retAdded
}

// parseOperationNameserverGetNameserversResult parses request result and return the string content
func parseOperationNameserverGetNameserversResult(resp0 *nameserver.GetNameserversOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*nameserver.GetNameserversDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*nameserver.GetNameserversOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelGetNameserversOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerGetNameserversOKBodyVersion(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerGetNameserversOKBodyData(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerGetNameserversOKBodyVersion(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	versionDescription := ``

	var versionFlagName string
	if cmdPrefix == "" {
		versionFlagName = "_version"
	} else {
		versionFlagName = fmt.Sprintf("%v._version", cmdPrefix)
	}

	var versionFlagDefault int64

	_ = cmd.PersistentFlags().Int64(versionFlagName, versionFlagDefault, versionDescription)

	return nil
}

func registerGetNameserversOKBodyData(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: data models.Nameservers array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGetNameserversOKBodyFlags(depth int, m *nameserver.GetNameserversOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, versionAdded := retrieveGetNameserversOKBodyVersionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || versionAdded

	err, dataAdded := retrieveGetNameserversOKBodyDataFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || dataAdded

	return nil, retAdded
}

func retrieveGetNameserversOKBodyVersionFlags(depth int, m *nameserver.GetNameserversOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	versionFlagName := fmt.Sprintf("%v._version", cmdPrefix)
	if cmd.Flags().Changed(versionFlagName) {

		var versionFlagName string
		if cmdPrefix == "" {
			versionFlagName = "_version"
		} else {
			versionFlagName = fmt.Sprintf("%v._version", cmdPrefix)
		}

		versionFlagValue, err := cmd.Flags().GetInt64(versionFlagName)
		if err != nil {
			return err, false
		}
		m.Version = versionFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveGetNameserversOKBodyDataFlags(depth int, m *nameserver.GetNameserversOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	dataFlagName := fmt.Sprintf("%v.data", cmdPrefix)
	if cmd.Flags().Changed(dataFlagName) {
		// warning: data array type models.Nameservers is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
