// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/practical-coder/hdt/client/acl_runtime"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDCmd returns a cmd to handle operation getServicesHaproxyRuntimeAclsId
func makeOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetServicesHaproxyRuntimeAclsID",
		Short: `Returns an ACL file by id using the runtime socket.`,
		RunE:  runOperationACLRuntimeGetServicesHaproxyRuntimeAclsID,
	}

	if err := registerOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationACLRuntimeGetServicesHaproxyRuntimeAclsID uses cmd flags to call endpoint api
func runOperationACLRuntimeGetServicesHaproxyRuntimeAclsID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := acl_runtime.NewGetServicesHaproxyRuntimeAclsIDParams()
	if err, _ := retrieveOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDResult(appCli.ACLRuntime.GetServicesHaproxyRuntimeAclsID(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDParamFlags registers all flags needed to fill params
func registerOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. ACL file entry ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDIDFlag(m *acl_runtime.GetServicesHaproxyRuntimeAclsIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDResult parses request result and return the string content
func parseOperationACLRuntimeGetServicesHaproxyRuntimeAclsIDResult(resp0 *acl_runtime.GetServicesHaproxyRuntimeAclsIDOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*acl_runtime.GetServicesHaproxyRuntimeAclsIDDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*acl_runtime.GetServicesHaproxyRuntimeAclsIDOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*acl_runtime.GetServicesHaproxyRuntimeAclsIDNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
