// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/practical-coder/hdc/models"
	"github.com/spf13/cobra"
)

// Schema cli for MonitorURI

// register flags to command
func registerModelMonitorURIFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelMonitorURIFlags(depth int, m *models.MonitorURI, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	return nil, retAdded
}
